import type {SnippetDefinition} from "./types";

const greek: Array<[string, string]> = [
    ["@a", "\\alpha"], ["@b", "\\beta"], ["@g", "\\gamma"], ["@G", "\\Gamma"],
    ["@d", "\\delta"], ["@D", "\\Delta"], ["@e", "\\epsilon"], [":e", "\\varepsilon"],
    ["@z", "\\zeta"], ["@t", "\\theta"], ["@T", "\\Theta"], ["@k", "\\kappa"],
    ["@l", "\\lambda"], ["@L", "\\Lambda"], ["@s", "\\sigma"], ["@S", "\\Sigma"],
    ["@o", "\\omega"], ["pi", "\\pi"], ["rho", "\\rho"], ["tau", "\\tau"],
    ["phi", "\\phi"], ["Phi", "\\Phi"], ["psi", "\\psi"], ["Psi", "\\Psi"],
    ["chi", "\\chi"], ["eta", "\\eta"], ["mu", "\\mu"], ["nu", "\\nu"],
    ["xi", "\\xi"], ["Xi", "\\Xi"], ["ome", "\\omega"],
    ["alpha", "\\alpha"], ["beta", "\\beta"], ["gamma", "\\gamma"], ["Gamma", "\\Gamma"],
    ["delta", "\\delta"], ["Delta", "\\Delta"], ["epsilon", "\\epsilon"], ["varepsilon", "\\varepsilon"],
    ["zeta", "\\zeta"], ["theta", "\\theta"], ["vartheta", "\\vartheta"], ["Theta", "\\Theta"],
    ["iota", "\\iota"], ["kappa", "\\kappa"], ["lambda", "\\lambda"], ["Lambda", "\\Lambda"],
    ["varrho", "\\varrho"], ["sigma", "\\sigma"], ["Sigma", "\\Sigma"],
    ["upsilon", "\\upsilon"], ["Upsilon", "\\Upsilon"], ["varphi", "\\varphi"],
    ["omega", "\\omega"], ["Omega", "\\Omega"], ["Pi", "\\Pi"],
];

export const DEFAULT_SNIPPETS: readonly SnippetDefinition[] = [
    ...greek.map(([trigger, replacement]) => ({trigger, replacement, options: "mAw", description: "Greek letter"})),
    {trigger: "//", replacement: "\\frac{$1}{$2}$0", options: "mA", priority: 100, description: "Empty fraction"},
    {trigger: ">=", replacement: "\\geq", options: "mA", description: "Greater than or equal"},
    {trigger: "<=", replacement: "\\leq", options: "mA", description: "Less than or equal"},
    {trigger: "!=", replacement: "\\neq", options: "mA", description: "Not equal"},
    {trigger: "->", replacement: "\\to", options: "mA", description: "Right arrow"},
    {trigger: "<-", replacement: "\\leftarrow", options: "mA", description: "Left arrow"},
    {trigger: "xx", replacement: "\\times", options: "mAw", description: "Multiplication"},
    {trigger: "oo", replacement: "\\infty", options: "mAw", description: "Infinity"},
    {trigger: "([A-Za-z0-9]|\\\\[A-Za-z]+)sr", replacement: "[[1]]^{2}", options: "mrA", priority: 20, description: "Square"},
    {trigger: "([A-Za-z0-9]|\\\\[A-Za-z]+)cb", replacement: "[[1]]^{3}", options: "mrA", priority: 20, description: "Cube"},
    {trigger: "([A-Za-z])([0-9])", replacement: "[[1]]_{[[2]]}", options: "mrA", priority: 10, description: "Numeric subscript"},
    {trigger: "([A-Za-z]|\\\\[A-Za-z]+)hat", replacement: "\\hat{[[1]]}", options: "mrA", description: "Hat accent"},
    {trigger: "([A-Za-z]|\\\\[A-Za-z]+)bar", replacement: "\\bar{[[1]]}", options: "mrA", description: "Bar accent"},
    {trigger: "([A-Za-z]|\\\\[A-Za-z]+)vec", replacement: "\\vec{[[1]]}", options: "mrA", description: "Vector accent"},
    {trigger: "([A-Za-z]|\\\\[A-Za-z]+)dot", replacement: "\\dot{[[1]]}", options: "mrA", description: "Dot accent"},
    {trigger: "frac", replacement: "\\frac{$1}{$2}$0", options: "m", description: "Fraction"},
    {trigger: "sq", replacement: "\\sqrt{$1}$0", options: "m", description: "Square root"},
    {trigger: "sum", replacement: "\\sum_{$1}^{$2} $0", options: "m", description: "Sum"},
    {trigger: "prod", replacement: "\\prod_{$1}^{$2} $0", options: "m", description: "Product"},
    {trigger: "int", replacement: "\\int_{$1}^{$2} $0 \\, d$3", options: "m", description: "Integral"},
    {trigger: "lim", replacement: "\\lim_{$1 \\to $2} $0", options: "m", description: "Limit"},
    {trigger: "text", replacement: "\\text{$1}$0", options: "m", description: "Text"},
    {trigger: "lr(", replacement: "\\left($1\\right)$0", options: "m", description: "Auto-sized parentheses"},
    {trigger: "cases", replacement: "\\begin{cases}\n  $1 & $2 \\\\\n  $3 & $4\n\\end{cases}$0", options: "m", description: "Cases"},
    {trigger: "mat", replacement: "\\begin{matrix}\n  $1 & $2 \\\\\n  $3 & $4\n\\end{matrix}$0", options: "m", description: "Matrix"},
    {trigger: "pmat", replacement: "\\begin{pmatrix}\n  $1 & $2 \\\\\n  $3 & $4\n\\end{pmatrix}$0", options: "m", description: "Parenthesized matrix"},
    {trigger: "align", replacement: "\\begin{aligned}\n  $1 &= $2 \\\\\n  $3 &= $4\n\\end{aligned}$0", options: "m", description: "Aligned equations"},
    {trigger: "U", replacement: "\\underbrace{[[selection]]}_{$1}$0", options: "mv", description: "Underbrace selection"},
    {trigger: "O", replacement: "\\overbrace{[[selection]]}^{$1}$0", options: "mv", description: "Overbrace selection"},
    {trigger: "C", replacement: "\\cancel{[[selection]]}$0", options: "mv", description: "Cancel selection"},
    {trigger: "K", replacement: "\\cancelto{$1}{[[selection]]}$0", options: "mv", description: "Cancel-to selection"},
    {trigger: "B", replacement: "\\underset{$1}{[[selection]]}$0", options: "mv", description: "Underset selection"},
];
